name: todolist 自动部署

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.2

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run build

      # 如果部署到 GitHub Pages
      - name: action-Deploy
      - uses: peaceiris/actions-gh-pages@v3
        with:
          BRANCH: gh-pages # 部署到 gh-pages 分支
          github_token: ${{ secrets.SOURCEMAPDEMO }}
          publish_dir: ./dist
