name: todolist 自动部署

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.17.1

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npm install

      - run: npm run build

      # 如果部署到 GitHub Pages
      - name: Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          branch: gh-pages # 部署到 gh-pages 分支
          github_token: ${{ secrets.SOURCEMAPDEMO }}
          publish_dir: ./dist
